version: '2'

services:

  nginx-reverse-proxy:
    image: nginx
    container_name: nginx-reverse-proxy
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /home/arcadas/.config/transmission:/config
      - /media/nas/torrent:/downloads
    expose:
      - 9091
      - 51413

  media-nginx:
    image: nginx
    container_name: media-nginx
    expose:
      - 80
    volumes:
      - /home/arcadas/github/dts2ac3-webgui:/www/media
      - /home/arcadas/github/arcadas-server/media/nginx/default.conf:/etc/nginx/conf.d/default.conf

  media-php:
    image: php:7.2-fpm
    container_name: media-php
    expose:
      - 9000
    volumes:
      - /home/arcadas/github/dts2ac3-webgui:/www/media
