version: '2'

services:

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=transmission.arcadas.com
      - VIRTUAL_PORT=9091
    volumes:
      #- /home/arcadas/.config/transmission:/config
      - ./settings.json:/config/settings.json
      - /media/nas/torrent:/downloads
    expose:
      - 9091
      - 51413
    networks:
      - proxy

networks:
  proxy:
    external: true

