version: '2'

services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    expose:
      - 9000
      - 8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.arcadas.com
      - VIRTUAL_PORT=9000
    networks:
      - proxy

networks:
  proxy:
    external: true
