version: '2'

services:
  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    network_mode: host
    environment:
      - MINIDLNA_MEDIA_DIR_1=/media/nas
      - MINIDLNA_MEDIA_DIR_2=/media/arcadas
    volumes:
      - /media/nas/movies:/media/nas
      - /media/arcadas/movies:/media/arcadas
    ports:
      - 8200:8200
    restart: unless-stopped
