version: '2'

services:

  nginx-reverse-proxy:
    image: nginx
    container_name: nginx-reverse-proxy
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80
    links:
     - transmission
     - media-nginx

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    volumes:
      - /home/arcadas/.config/transmission:/config
      - /media/nas/torrent:/downloads
    expose:
      - 9091
      - 51413

  media-nginx:
    image: nginx
    container_name: media-nginx
    expose:
      - 80
    volumes:
      - /home/arcadas/github/dts2ac3-webgui:/www/media
      - /home/arcadas/github/arcadas-server/media/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - media-php

  media-php:
    build: /home/arcadas/github/arcadas-server/media/php
    container_name: media-php
    expose:
      - 9000
    volumes:
      - /home/arcadas/github/dts2ac3-webgui:/www/media
      - /media/nas/movies:/media/nas/movies
