version: '2'

services:

  media-nginx:
    image: nginx
    container_name: media-nginx
    expose:
      - 80
    volumes:
      - /home/arcadas/github/dts2ac3-webgui:/www/media
      - /home/arcadas/github/arcadas-server/media/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - media-php
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cal.rule=Host(`media.arcadas.com`)"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.cal.loadbalancer.server.port=80"

  media-php:
    image: php-fpm-mkv
    container_name: media-php
    expose:
      - 9000
    volumes:
      - /home/arcadas/github/dts2ac3-webgui:/www/media
      - /media/nas/movies:/media/nas/movies
    networks:
      - proxy

networks:
  proxy:
    external: true
