---
version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - TRANSMISSION_WEB_HOME=/kettu/
      - VIRTUAL_HOST=transmission.arcadas.com
    volumes:
      - /home/arcadas/.config/transmission:/config
      - /media/nas/torrent:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
